### ISSUE TITLE
[BUG]: CustomUser is not JSON serializable

### ISSUE THREAD

**Issue by sirateek** [GarnBarn/garnbarn-backend#29]
## Describe the bug
Calling the GET All API returning the 500 telling that `CustomUser is not JSON serializable`

## Step To Reproduce the bug:

(1-3 is done in Admin page)
1. Create the CustomUser object.
2. Create the assignment then assign the author to the assignment with the created CustomUser
3. Call the GET All assignment API.
4. API Return 500 and the server crashed.

## Expected behavior

This should return the assignment object containing the `uid` instead of the entire CustomUser object.

## Error example
```
Internal Server Error: /api/v1/assignment/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CustomUser is not JSON serializable
[02/Nov/2021 16:37:06] "GET /api/v1/assignment/ HTTP/1.1" 500 129485
```

## Example data
![Screen Shot 2564-11-02 at 23 40 28](https://user-images.githubusercontent.com/25188615/139908041-ffeb15a4-b738-49a0-b3c1-95e6327a0421.png)

**Comment by sirateek** [comment]
This bug is critical!. It breaks the Get Assignment All API. Please investigate this ASAP and merge it into master as a HotFix.

**Comment by sirateek** [comment]
By using bisect, I found that the first commit that this bug has been introduced is cf81fc7a287417bad57aaad5cb6a547eff0441f6
