### ISSUE TITLE
[BUG]: The web show error code status code 500 when change time to notify.

### ISSUE THREAD

**Issue by Jakarin-Jojo** [GarnBarn/garnbarn-backend#52]
## Describe the bug

When click to change time to notify in the assignment. The web show error code status code 500.

## Step To Reproduce the bug:

1. Go to the home page and login
2. Click on the assignment
3. Click on the edit button
4. Click on Notification Settings
5. Change time to notice before the due date.
6. Click on save
7. See Error code status code 500

## Expected behavior

The Web should not show error code status code 500.

## Screenshots
![image](https://user-images.githubusercontent.com/72879083/143427951-55a60fda-3eba-4f81-981c-f608190fd836.png)

## Hardware Spec (please complete the following information):

- Device: [Computer
- OS: Window11
- Browser Microsoft Edge
- Version 96.0.1054.29 (Official Build) (64-bit)

**Comment by sirateek** [comment]
Here is some of the server log. (Already hide the sensitive data as `<HIDDEN>`)
```log
[Thu Nov 25 17:34:39.869927 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>] [(ERROR) 21/Nov/2021 17:34:39] Internal Server Error: /api/v1/assignment/53/
[Thu Nov 25 17:34:39.869959 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>] Traceback (most recent call last):
[Thu Nov 25 17:34:39.869964 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/apscheduler/util.py", line 304, in ref_to_obj
[Thu Nov 25 17:34:39.869969 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     obj = __import__(modulename, fromlist=[rest])
[Thu Nov 25 17:34:39.869973 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>] ModuleNotFoundError: No module named 'garnbarn_api.services.pubsub'
[Thu Nov 25 17:34:39.869977 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>] 
[Thu Nov 25 17:34:39.869980 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>] During handling of the above exception, another exception occurred:
[Thu Nov 25 17:34:39.869984 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>] 
[Thu Nov 25 17:34:39.869987 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>] Traceback (most recent call last):
[Thu Nov 25 17:34:39.869991 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Thu Nov 25 17:34:39.869995 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     response = get_response(request)
[Thu Nov 25 17:34:39.869999 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Thu Nov 25 17:34:39.870002 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Nov 25 17:34:39.870006 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Thu Nov 25 17:34:39.870010 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     return view_func(*args, **kwargs)
[Thu Nov 25 17:34:39.870014 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
[Thu Nov 25 17:34:39.870017 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     return self.dispatch(request, *args, **kwargs)
[Thu Nov 25 17:34:39.870021 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
[Thu Nov 25 17:34:39.870025 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     response = self.handle_exception(exc)
[Thu Nov 25 17:34:39.870028 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
[Thu Nov 25 17:34:39.870044 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     self.raise_uncaught_exception(exc)
[Thu Nov 25 17:34:39.870047 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Thu Nov 25 17:34:39.870050 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     raise exc
[Thu Nov 25 17:34:39.870054 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
[Thu Nov 25 17:34:39.870057 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     response = handler(request, *args, **kwargs)
[Thu Nov 25 17:34:39.870060 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarn_api/views.py", line 181, in partial_update
[Thu Nov 25 17:34:39.870064 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     self.perform_update(serializer)
[Thu Nov 25 17:34:39.870067 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/rest_framework/mixins.py", line 78, in perform_update
[Thu Nov 25 17:34:39.870070 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     serializer.save()
[Thu Nov 25 17:34:39.870073 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/rest_framework/serializers.py", line 200, in save
[Thu Nov 25 17:34:39.870077 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     self.instance = self.update(self.instance, validated_data)
[Thu Nov 25 17:34:39.870080 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/rest_framework/serializers.py", line 983, in update
[Thu Nov 25 17:34:39.870083 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     instance.save()
[Thu Nov 25 17:34:39.870086 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
[Thu Nov 25 17:34:39.870090 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     self.save_base(using=using, force_insert=force_insert,
[Thu Nov 25 17:34:39.870093 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/django/db/models/base.py", line 774, in save_base
[Thu Nov 25 17:34:39.870096 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     post_save.send(
[Thu Nov 25 17:34:39.870099 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
[Thu Nov 25 17:34:39.870103 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     return [
[Thu Nov 25 17:34:39.870106 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
[Thu Nov 25 17:34:39.870109 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     (receiver, receiver(signal=self, sender=sender, **named))
[Thu Nov 25 17:34:39.870116 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarn_api/signals/on_save_assignment_signal.py", line 27, in on_save_assignment
[Thu Nov 25 17:34:39.870119 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     clear_jobs(instance)
[Thu Nov 25 17:34:39.870122 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarn_api/signals/on_save_assignment_signal.py", line 77, in clear_jobs
[Thu Nov 25 17:34:39.870126 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     if scheduler.get_job(job_id) is None:
[Thu Nov 25 17:34:39.870129 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 591, in get_job
[Thu Nov 25 17:34:39.870132 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     return self._lookup_job(job_id, jobstore)[0]
[Thu Nov 25 17:34:39.870135 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 817, in _lookup_job
[Thu Nov 25 17:34:39.870139 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     job = store.lookup_job(job_id)
[Thu Nov 25 17:34:39.870142 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/django_apscheduler/util.py", line 99, in func_wrapper
[Thu Nov 25 17:34:39.870145 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     result = func(*args, **kwargs)
[Thu Nov 25 17:34:39.870148 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/django_apscheduler/jobstores.py", line 208, in lookup_job
[Thu Nov 25 17:34:39.870152 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     return self._reconstitute_job(job_state) if job_state else None
[Thu Nov 25 17:34:39.870155 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/django_apscheduler/jobstores.py", line 281, in _reconstitute_job
[Thu Nov 25 17:34:39.870159 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     job.__setstate__(job_state)
[Thu Nov 25 17:34:39.870162 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/apscheduler/job.py", line 273, in __setstate__
[Thu Nov 25 17:34:39.870165 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     self.func = ref_to_obj(self.func_ref)
[Thu Nov 25 17:34:39.870168 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]   File "<HIDDEN>/garnbarn-backend/garnbarnenv/lib/python3.8/site-packages/apscheduler/util.py", line 306, in ref_to_obj
[Thu Nov 25 17:34:39.870172 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>]     raise LookupError('Error resolving reference %s: could not import module' % ref)
[Thu Nov 25 17:34:39.870175 2021] [wsgi:error] [<HIDDEN>] [report <HIDDEN>] LookupError: Error resolving reference garnbarn_api.services.pubsub:pubsub: could not import module
```

**Comment by abounk** [comment]
@Jakarin-Jojo 
We are so sorry that this happened. It's because we have not cleaned our database yet, and this assignment still using the old data.

We are planning to clear our database by this Sunday at 11:59 pm. Thank you for bringing this to our attention.
